// react-ts-project/src/components/project/components/Button/button.tsx
import React from 'react'
import classNames from 'classnames';
//枚举按钮大小
export enum ButtonSize {
    Large = 'lg',
    Small = 'sm',
}

export enum ButtonType {
    Primary = 'primary',
    Default = 'default',
    Danger = 'danger',
    Link = 'link',
}

interface BaseButtonProps {
    className?: string
    disabled?: boolean;
    size?: ButtonSize;
    btnType?: ButtonType;
    children?: React.ReactNode;
    href?: string;
}
type NativeButtonProps = BaseButtonProps & React.ButtonHTMLAttributes<HTMLElement>
type AnchorButtonProps = BaseButtonProps & React.AnchorHTMLAttributes<HTMLElement>
export type ButtonProps = Partial<NativeButtonProps & AnchorButtonProps>

const Button: React.FC<ButtonProps> = (props) => {
    console.log(props)
    const {
        disabled, className, size, btnType, children, href, ...restProps
    } = props
    const classes = classNames('btn', className, {
        [`btn-${btnType}`]: btnType,
        [`btn-${size}`]: size,
        'disabled': (btnType === ButtonType.Link) && disabled
    })
    if (btnType === ButtonType.Link && href) {
        return (
            <a {...restProps} className={classes} href={href}>{children}</a>
        )
    } else {
        return (
            <button {...restProps} className={classes} disabled={disabled}>{children}</button>
        )
    }
}
Button.defaultProps = {
    disabled: false,
    btnType: ButtonType.Default
}
export default Button

// vue3-project/src/project/src/Button/button.vue
<template>
    <div>button</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

//枚举按钮大小
export enum ButtonSize {
    Large = 'lg',
    Small = 'sm',
}

export enum ButtonType {
    Primary = 'primary',
    Default = 'default',
    Danger = 'danger',
    Link = 'link',
}

interface BaseButtonProps {
    class?: string
    disabled?: boolean;
    size?: ButtonSize;
    btnType?: ButtonType;
    children?: any;
    href?: string;
}
type NativeButtonProps = BaseButtonProps
type AnchorButtonProps = BaseButtonProps
export type ButtonProps = Partial<NativeButtonProps & AnchorButtonProps>

export default defineComponent({
    setup(props: ButtonProps) {
        console.log(props,'props')
        const {
        disabled,  size, btnType, children, href, ...restProps
    } = props
    }
})

</script>
<style lang="scss" scoped></style>
